export {default as Home} from './Home/Home.jsx'
export {default as Navbar} from './Navbar/Navbar.jsx'
export {default as Footer} from './Footer/Footer.jsx'
export {default as Login} from './Login/Login.jsx'
export {default as Categories} from './Categories/Categories.jsx'
export {default as Brands} from './Brands/Brands.jsx'
export {default as Product} from './Product/Product.jsx'
export {default as Products} from './Products/Products.jsx'
export {default as Register} from './Register/Register.jsx'
export {default as NotFound} from './NotFound/NotFound.jsx'
export {default as LayOut} from './LayOut/LayOut.jsx'
export {default as RecentProducts} from './RecentProducts/RecentProducts.jsx'
export {default as ProductDetails} from './ProductDetails/ProductDetails.jsx'
export {default as Cart} from './Cart/Cart.jsx'
export {default as Item} from './Item/Item.jsx'
export {default as Allorders} from './Allorders/Allorders.jsx'
export {default as Address} from './Address/Address.jsx'

